alert('Raiden Shogun é MINHA mommy!')
var visões_adiquiridas = parseInt(prompt("Quantas visões vc tem?"))
if(visões_adiquiridas>0)
alert("Você possui "+ visões_adiquiridas+ " a mais que o permitido!" )
if(visões_adiquiridas==0)
alert("PARABÉNS, você é um cidadão exemplar!")
if(visões_adiquiridas<0)
alert("Fic")
